### ISSUE TITLE
Background image and video is not working.

### ISSUE THREAD

**Issue by rare25** [hozuki/MilliSim#17]
For image, the correct path is specified, but it is not loaded.
For video, ffmpeg is placed, but MilliSim does not run.

**Comment by hozuki** [comment]
Would you mind run it with `--debug` switch, and see what happened in `log-file.txt`?

---

Here is an example of how to place FFmpeg libraries:

```
|- TheaterDays.Direct3D11.exe
|- x86
    |- avcodec-57.dll
    |- avdevice-57.dll
    |- ...
```

BGI configuration ("data" section):

```yaml
data:
  bgi: Contents/res/img/bg/base_light.jpg # note: Absolute path and Windows path separator ('\') are also acceptable
  fit: letter_box
```
